# %PLAYER%: Player name
# %SERVER%: Server name
transfer-timer:
  enabled: true
  second: 3
  message: "&bYou will be transferred in &e%SECOND% &bseconds"

player-transfer-message: "&e%PLAYER% &bhas been transferred to the &e%SERVER%"

menu:
  enabled: true
  title: "Servers"

servers:
  lobby:
    command: lobby
    address: 127.0.0.1
    port: "19132"
    description: lobby server
    aliases:
      - hub
    image-type: url
    image: https://gamepedia.cursecdn.com/minecraft_gamepedia/thumb/d/d6/Nether_Bricks.png/150px-Nether_Bricks.png?version=389147a764733d6b6fe4053cd2411316
  survival:
    command: survival
    address: 127.0.0.1
    port: 19131
    description: survival server
    aliases: []
    image-type: path
    image: textures/items/iron_pickaxe